### ISSUE TITLE
Add MongoDb driver

### ISSUE THREAD

**Issue by websoftwares** [LateRegistration/lr-restify#3]
Add DocumentDb driver to the image

**Comment by rodislav** [comment]
can we do it in your space ?

**Comment by websoftwares** [comment]
Yes go ahead and use it.

**Comment by websoftwares** [comment]
dbs/sample%20database/colls/sample%20collection
{ code: 401,
  body: '{"code":"Unauthorized","message":"The input authorization token can\'t serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: \'post\\ndocs\\ndbs/sample database/colls/sample collection\\nwed, 06 apr 2016 22:03:52 gmt\\n\\n\'\\r\\nActivityId: 80113b37-0c03-4be4-b839-31c1d9ef0df7"}' }

**Comment by websoftwares** [comment]
time is same as local machine

**Comment by websoftwares** [comment]
dbs/sample%20database
{ code: 401,
  body: '{"code":"Unauthorized","message":"The input authorization token can\'t serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: \'post\\ncolls\\ndbs/sample database\\nwed, 06 apr 2016 22:21:39 gmt\\n\\n\'\\r\\nActivityId: a0486bbe-d58a-4345-b52c-56e92dde6f3e"}' } undefined

**Comment by websoftwares** [comment]
some queries are working some not because of this if it is to much of a problem i suggest we switch to PostgreSQL with JSON-B

**Comment by websoftwares** [comment]
@rodislav check this out

**Comment by websoftwares** [comment]
Ok forget it, lets go with mongo.

- Create DockerFile for Mongo (defaults)
- Create repository.
- Add readme.
- Deploy to @rodislav docker engine vm 
- In this repository add mongoose and refactor the databaseconnection singleton to use mongogoose (mongo driver)
- Use the example model and update the respond callback in app.js
- Server some json (no p)
