### ISSUE TITLE
Add api doc run command to deployment

### ISSUE THREAD

**Issue by websoftwares** [LateRegistration/lr-restify#47]
npm run apidoc

**Comment by websoftwares** [comment]
Actually it would be more  nice to have a nginx and set the output to this machine either scp it over or network mount the volume from lr restify.

**Comment by rodislav** [comment]
for now we'll run like this: `apidoc -i src/ -o apidoc/` because npm run apidoc requires a custom template, but is easier for now to not make it

I have created also a file bash-examples.sh where I wrote the command to generate apidocs
